version: '3.8'

services:
  backend:
    build:
      context: ./backend-api
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest

volumes:
  mongo-data:
